// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZVMCOrgk_tiFfdLDrpkXRt5_EhaM6cMM',
    appId: '1:285515668411:web:eaa4d6c87f7449784d029e',
    messagingSenderId: '285515668411',
    projectId: 'fooddeliveryapp-737ba',
    authDomain: 'fooddeliveryapp-737ba.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-737ba.firebasestorage.app',
    measurementId: 'G-WMH99MQND4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZCcopCClqzgy_MxSW0ig40JxRUYNPRQ',
    appId: '1:285515668411:android:1a5d988d424ccc294d029e',
    messagingSenderId: '285515668411',
    projectId: 'fooddeliveryapp-737ba',
    storageBucket: 'fooddeliveryapp-737ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SDo2jJ-yvA55VclQU9gAfAKcwlxnLa4',
    appId: '1:285515668411:ios:ee5231257325a3d94d029e',
    messagingSenderId: '285515668411',
    projectId: 'fooddeliveryapp-737ba',
    storageBucket: 'fooddeliveryapp-737ba.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6SDo2jJ-yvA55VclQU9gAfAKcwlxnLa4',
    appId: '1:285515668411:ios:ee5231257325a3d94d029e',
    messagingSenderId: '285515668411',
    projectId: 'fooddeliveryapp-737ba',
    storageBucket: 'fooddeliveryapp-737ba.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZVMCOrgk_tiFfdLDrpkXRt5_EhaM6cMM',
    appId: '1:285515668411:web:dbff1f855424f3b94d029e',
    messagingSenderId: '285515668411',
    projectId: 'fooddeliveryapp-737ba',
    authDomain: 'fooddeliveryapp-737ba.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-737ba.firebasestorage.app',
    measurementId: 'G-KT8GF19ESP',
  );
}
